name: injectzone
description: "A zone-based dependency injection package"
version: 0.0.1
homepage: https://github.com/leonus96/injectzone

environment:
  sdk: '>=3.3.4 <4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.9
